// indonesianLocations.ts
export const indonesianLocations = [
  // Aceh
  { value: 'South Aceh Regency, Aceh', label: 'South Aceh Regency, Aceh' },
  { value: 'Southeast Aceh Regency, Aceh', label: 'Southeast Aceh Regency, Aceh' },
  { value: 'East Aceh Regency, Aceh', label: 'East Aceh Regency, Aceh' },
  { value: 'Central Aceh Regency, Aceh', label: 'Central Aceh Regency, Aceh' },
  { value: 'West Aceh Regency, Aceh', label: 'West Aceh Regency, Aceh' },
  { value: 'Aceh Besar Regency, Aceh', label: 'Aceh Besar Regency, Aceh' },
  { value: 'Pidie Regency, Aceh', label: 'Pidie Regency, Aceh' },
  { value: 'North Aceh Regency, Aceh', label: 'North Aceh Regency, Aceh' },
  { value: 'Simeulue Regency, Aceh', label: 'Simeulue Regency, Aceh' },
  { value: 'Aceh Singkil Regency, Aceh', label: 'Aceh Singkil Regency, Aceh' },
  { value: 'Bireuën Regency, Aceh', label: 'Bireuën Regency, Aceh' },
  { value: 'Southwest Aceh Regency, Aceh', label: 'Southwest Aceh Regency, Aceh' },
  { value: 'Gayo Lues Regency, Aceh', label: 'Gayo Lues Regency, Aceh' },
  { value: 'Aceh Jaya Regency, Aceh', label: 'Aceh Jaya Regency, Aceh' },
  { value: 'Nagan Raya Regency, Aceh', label: 'Nagan Raya Regency, Aceh' },
  { value: 'Aceh Tamiang Regency, Aceh', label: 'Aceh Tamiang Regency, Aceh' },
  { value: 'Bener Meriah Regency, Aceh', label: 'Bener Meriah Regency, Aceh' },
  { value: 'Pidie Jaya Regency, Aceh', label: 'Pidie Jaya Regency, Aceh' },
  { value: 'Banda Aceh City, Aceh', label: 'Banda Aceh City, Aceh' },
  { value: 'Sabang City, Aceh', label: 'Sabang City, Aceh' },
  { value: 'Lhokseumawe City, Aceh', label: 'Lhokseumawe City, Aceh' },
  { value: 'Langsa City, Aceh', label: 'Langsa City, Aceh' },
  { value: 'Subulussalam City, Aceh', label: 'Subulussalam City, Aceh' },

  // North Sumatra
  { value: 'Asahan Regency, North Sumatra', label: 'Asahan Regency, North Sumatra' },
  { value: 'Batubara Regency, North Sumatra', label: 'Batubara Regency, North Sumatra' },
  { value: 'Central Tapanuli Regency, North Sumatra', label: 'Central Tapanuli Regency, North Sumatra' },
  { value: 'Dairi Regency, North Sumatra', label: 'Dairi Regency, North Sumatra' },
  { value: 'Deli Serdang Regency, North Sumatra', label: 'Deli Serdang Regency, North Sumatra' },
  { value: 'Humbang Hasundutan Regency, North Sumatra', label: 'Humbang Hasundutan Regency, North Sumatra' },
  { value: 'Karo Regency, North Sumatra', label: 'Karo Regency, North Sumatra' },
  { value: 'Labuhan Batu Regency, North Sumatra', label: 'Labuhan Batu Regency, North Sumatra' },
  { value: 'Langkat Regency, North Sumatra', label: 'Langkat Regency, North Sumatra' },
  { value: 'Mandailing Natal Regency, North Sumatra', label: 'Mandailing Natal Regency, North Sumatra' },
  { value: 'Nias Regency, North Sumatra', label: 'Nias Regency, North Sumatra' },
  { value: 'North Labuhan Batu Regency, North Sumatra', label: 'North Labuhan Batu Regency, North Sumatra' },
  { value: 'North Nias Regency, North Sumatra', label: 'North Nias Regency, North Sumatra' },
  { value: 'North Padang Lawas Regency, North Sumatra', label: 'North Padang Lawas Regency, North Sumatra' },
  { value: 'North Tapanuli Regency, North Sumatra', label: 'North Tapanuli Regency, North Sumatra' },
  { value: 'Padang Lawas Regency, North Sumatra', label: 'Padang Lawas Regency, North Sumatra' },
  { value: 'Pakpak Bharat Regency, North Sumatra', label: 'Pakpak Bharat Regency, North Sumatra' },
  { value: 'Samosir Regency, North Sumatra', label: 'Samosir Regency, North Sumatra' },
  { value: 'Serdang Bedagai Regency, North Sumatra', label: 'Serdang Bedagai Regency, North Sumatra' },
  { value: 'Simalungun Regency, North Sumatra', label: 'Simalungun Regency, North Sumatra' },
  { value: 'South Labuhan Batu Regency, North Sumatra', label: 'South Labuhan Batu Regency, North Sumatra' },
  { value: 'South Nias Regency, North Sumatra', label: 'South Nias Regency, North Sumatra' },
  { value: 'South Tapanuli Regency, North Sumatra', label: 'South Tapanuli Regency, North Sumatra' },
  { value: 'Toba Regency, North Sumatra', label: 'Toba Regency, North Sumatra' },
  { value: 'West Nias Regency, North Sumatra', label: 'West Nias Regency, North Sumatra' },
  { value: 'Binjai City, North Sumatra', label: 'Binjai City, North Sumatra' },
  { value: 'Gunungsitoli City, North Sumatra', label: 'Gunungsitoli City, North Sumatra' },
  { value: 'Medan City, North Sumatra', label: 'Medan City, North Sumatra' },
  { value: 'Padang Sidempuan City, North Sumatra', label: 'Padang Sidempuan City, North Sumatra' },
  { value: 'Pematangsiantar City, North Sumatra', label: 'Pematangsiantar City, North Sumatra' },
  { value: 'Sibolga City, North Sumatra', label: 'Sibolga City, North Sumatra' },
  { value: 'Tanjungbalai City, North Sumatra', label: 'Tanjungbalai City, North Sumatra' },
  { value: 'Tebing Tinggi City, North Sumatra', label: 'Tebing Tinggi City, North Sumatra' },

  // West Sumatra
  { value: 'Agam Regency, West Sumatra', label: 'Agam Regency, West Sumatra' },
  { value: 'Dharmasraya Regency, West Sumatra', label: 'Dharmasraya Regency, West Sumatra' },
  { value: 'Lima Puluh Kota Regency, West Sumatra', label: 'Lima Puluh Kota Regency, West Sumatra' },
  { value: 'Mentawai Islands Regency, West Sumatra', label: 'Mentawai Islands Regency, West Sumatra' },
  { value: 'Padang Pariaman Regency, West Sumatra', label: 'Padang Pariaman Regency, West Sumatra' },
  { value: 'Pasaman Regency, West Sumatra', label: 'Pasaman Regency, West Sumatra' },
  { value: 'Sijunjung Regency, West Sumatra', label: 'Sijunjung Regency, West Sumatra' },
  { value: 'Solok Regency, West Sumatra', label: 'Solok Regency, West Sumatra' },
  { value: 'Pesisir Selatan Regency, West Sumatra', label: 'Pesisir Selatan Regency, West Sumatra' },
  { value: 'South Solok Regency, West Sumatra', label: 'South Solok Regency, West Sumatra' },
  { value: 'Tanah Datar Regency, West Sumatra', label: 'Tanah Datar Regency, West Sumatra' },
  { value: 'West Pasaman Regency, West Sumatra', label: 'West Pasaman Regency, West Sumatra' },
  { value: 'Bukittinggi City, West Sumatra', label: 'Bukittinggi City, West Sumatra' },
  { value: 'Padang City, West Sumatra', label: 'Padang City, West Sumatra' },
  { value: 'Padang Panjang City, West Sumatra', label: 'Padang Panjang City, West Sumatra' },
  { value: 'Pariaman City, West Sumatra', label: 'Pariaman City, West Sumatra' },
  { value: 'Payakumbuh City, West Sumatra', label: 'Payakumbuh City, West Sumatra' },
  { value: 'Sawahlunto City, West Sumatra', label: 'Sawahlunto City, West Sumatra' },
  { value: 'Solok City, West Sumatra', label: 'Solok City, West Sumatra' },

  // Jambi
  { value: 'Batang Hari Regency, Jambi', label: 'Batang Hari Regency, Jambi' },
  { value: 'Bungo Regency, Jambi', label: 'Bungo Regency, Jambi' },
  { value: 'East Tanjung Jabung Regency, Jambi', label: 'East Tanjung Jabung Regency, Jambi' },
  { value: 'Kerinci Regency, Jambi', label: 'Kerinci Regency, Jambi' },
  { value: 'Merangin Regency, Jambi', label: 'Merangin Regency, Jambi' },
  { value: 'Muaro Jambi Regency, Jambi', label: 'Muaro Jambi Regency, Jambi' },
  { value: 'Sarolangun Regency, Jambi', label: 'Sarolangun Regency, Jambi' },
  { value: 'Tebo Regency, Jambi', label: 'Tebo Regency, Jambi' },
  { value: 'West Tanjung Jabung Regency, Jambi', label: 'West Tanjung Jabung Regency, Jambi' },
  { value: 'Jambi City, Jambi', label: 'Jambi City, Jambi' },
  { value: 'Sungai Penuh City, Jambi', label: 'Sungai Penuh City, Jambi' },

  // Riau
  { value: 'Bengkalis Regency, Riau', label: 'Bengkalis Regency, Riau' },
  { value: 'Indragiri Hilir Regency, Riau', label: 'Indragiri Hilir Regency, Riau' },
  { value: 'Indragiri Hulu Regency, Riau', label: 'Indragiri Hulu Regency, Riau' },
  { value: 'Kampar Regency, Riau', label: 'Kampar Regency, Riau' },
  { value: 'Kuantan Singingi Regency, Riau', label: 'Kuantan Singingi Regency, Riau' },
  { value: 'Meranti Islands Regency, Riau', label: 'Meranti Islands Regency, Riau' },
  { value: 'Pelalawan Regency, Riau', label: 'Pelalawan Regency, Riau' },
  { value: 'Rokan Hulu Regency, Riau', label: 'Rokan Hulu Regency, Riau' },
  { value: 'Rokan Hilir Regency, Riau', label: 'Rokan Hilir Regency, Riau' },
  { value: 'Siak Regency, Riau', label: 'Siak Regency, Riau' },
  { value: 'Dumai City, Riau', label: 'Dumai City, Riau' },
  { value: 'Pekanbaru City, Riau', label: 'Pekanbaru City, Riau' },

  // Bengkulu
  { value: 'Central Bengkulu Regency, Bengkulu', label: 'Central Bengkulu Regency, Bengkulu' },
  { value: 'Kaur Regency, Bengkulu', label: 'Kaur Regency, Bengkulu' },
  { value: 'Kepahiang Regency, Bengkulu', label: 'Kepahiang Regency, Bengkulu' },
  { value: 'Lebong Regency, Bengkulu', label: 'Lebong Regency, Bengkulu' },
  { value: 'Mukomuko Regency, Bengkulu', label: 'Mukomuko Regency, Bengkulu' },
  { value: 'North Bengkulu Regency, Bengkulu', label: 'North Bengkulu Regency, Bengkulu' },
  { value: 'Rejang Lebong Regency, Bengkulu', label: 'Rejang Lebong Regency, Bengkulu' },
  { value: 'Seluma Regency, Bengkulu', label: 'Seluma Regency, Bengkulu' },
  { value: 'South Bengkulu Regency, Bengkulu', label: 'South Bengkulu Regency, Bengkulu' },
  { value: 'Bengkulu City, Bengkulu', label: 'Bengkulu City, Bengkulu' },

  // South Sumatra
  { value: 'Banyuasin Regency, South Sumatra', label: 'Banyuasin Regency, South Sumatra' },
  { value: 'East Ogan Komering Ulu Regency, South Sumatra', label: 'East Ogan Komering Ulu Regency, South Sumatra' },
  { value: 'Empat Lawang Regency, South Sumatra', label: 'Empat Lawang Regency, South Sumatra' },
  { value: 'Lahat Regency, South Sumatra', label: 'Lahat Regency, South Sumatra' },
  { value: 'Muara Enim Regency, South Sumatra', label: 'Muara Enim Regency, South Sumatra' },
  { value: 'Musi Banyuasin Regency, South Sumatra', label: 'Musi Banyuasin Regency, South Sumatra' },
  { value: 'Musi Rawas Regency, South Sumatra', label: 'Musi Rawas Regency, South Sumatra' },
  { value: 'North Musi Rawas Regency, South Sumatra', label: 'North Musi Rawas Regency, South Sumatra' },
  { value: 'Ogan Ilir Regency, South Sumatra', label: 'Ogan Ilir Regency, South Sumatra' },
  { value: 'Ogan Komering Ilir Regency, South Sumatra', label: 'Ogan Komering Ilir Regency, South Sumatra' },
  { value: 'Ogan Komering Ulu Regency, South Sumatra', label: 'Ogan Komering Ulu Regency, South Sumatra' },
  { value: 'Penukal Abab Lematang Ilir Regency, South Sumatra', label: 'Penukal Abab Lematang Ilir Regency, South Sumatra' },
  { value: 'South Ogan Komering Ulu Regency, South Sumatra', label: 'South Ogan Komering Ulu Regency, South Sumatra' },
  { value: 'Lubuklinggau City, South Sumatra', label: 'Lubuklinggau City, South Sumatra' },
  { value: 'Pagar Alam City, South Sumatra', label: 'Pagar Alam City, South Sumatra' },
  { value: 'Palembang City, South Sumatra', label: 'Palembang City, South Sumatra' },
  { value: 'Prabumulih City, South Sumatra', label: 'Prabumulih City, South Sumatra' },

  // Lampung
  { value: 'Central Lampung Regency, Lampung', label: 'Central Lampung Regency, Lampung' },
  { value: 'East Lampung Regency, Lampung', label: 'East Lampung Regency, Lampung' },
  { value: 'Mesuji Regency, Lampung', label: 'Mesuji Regency, Lampung' },
  { value: 'North Lampung Regency, Lampung', label: 'North Lampung Regency, Lampung' },
  { value: 'Pesawaran Regency, Lampung', label: 'Pesawaran Regency, Lampung' },
  { value: 'Pringsewu Regency, Lampung', label: 'Pringsewu Regency, Lampung' },
  { value: 'South Lampung Regency, Lampung', label: 'South Lampung Regency, Lampung' },
  { value: 'Tanggamus Regency, Lampung', label: 'Tanggamus Regency, Lampung' },
  { value: 'Tulang Bawang Regency, Lampung', label: 'Tulang Bawang Regency, Lampung' },
  { value: 'Way Kanan Regency, Lampung', label: 'Way Kanan Regency, Lampung' },
  { value: 'West Lampung Regency, Lampung', label: 'West Lampung Regency, Lampung' },
  { value: 'Pesisir Barat Regency, Lampung', label: 'Pesisir Barat Regency, Lampung' },
  { value: 'West Tulang Bawang Regency, Lampung', label: 'West Tulang Bawang Regency, Lampung' },
  { value: 'Bandar Lampung City, Lampung', label: 'Bandar Lampung City, Lampung' },
  { value: 'Metro City, Lampung', label: 'Metro City, Lampung' },

  // Bangka Belitung Islands
  { value: 'Bangka Regency, Bangka Belitung Islands', label: 'Bangka Regency, Bangka Belitung Islands' },
  { value: 'Belitung Regency, Bangka Belitung Islands', label: 'Belitung Regency, Bangka Belitung Islands' },
  { value: 'South Bangka Regency, Bangka Belitung Islands', label: 'South Bangka Regency, Bangka Belitung Islands' },
  { value: 'Central Bangka Regency, Bangka Belitung Islands', label: 'Central Bangka Regency, Bangka Belitung Islands' },
  { value: 'West Bangka Regency, Bangka Belitung Islands', label: 'West Bangka Regency, Bangka Belitung Islands' },
  { value: 'East Belitung Regency, Bangka Belitung Islands', label: 'East Belitung Regency, Bangka Belitung Islands' },
  { value: 'Pangkal Pinang City, Bangka Belitung Islands', label: 'Pangkal Pinang City, Bangka Belitung Islands' },

  // Riau Islands
  { value: 'Anambas Islands Regency, Riau Islands', label: 'Anambas Islands Regency, Riau Islands' },
  { value: 'Bintan Regency, Riau Islands', label: 'Bintan Regency, Riau Islands' },
  { value: 'Karimun Regency, Riau Islands', label: 'Karimun Regency, Riau Islands' },
  { value: 'Lingga Regency, Riau Islands', label: 'Lingga Regency, Riau Islands' },
  { value: 'Natuna Regency, Riau Islands', label: 'Natuna Regency, Riau Islands' },
  { value: 'Batam City, Riau Islands', label: 'Batam City, Riau Islands' },
  { value: 'Tanjung Pinang City, Riau Islands', label: 'Tanjung Pinang City, Riau Islands' },

  // Special Region of Jakarta
  { value: 'Thousand Islands Regency, Special Region of Jakarta', label: 'Thousand Islands Regency, Special Region of Jakarta' },
  { value: 'Central Jakarta City, Special Region of Jakarta', label: 'Central Jakarta City, Special Region of Jakarta' },
  { value: 'East Jakarta City, Special Region of Jakarta', label: 'East Jakarta City, Special Region of Jakarta' },
  { value: 'North Jakarta City, Special Region of Jakarta', label: 'North Jakarta City, Special Region of Jakarta' },
  { value: 'South Jakarta City, Special Region of Jakarta', label: 'South Jakarta City, Special Region of Jakarta' },
  { value: 'West Jakarta City, Special Region of Jakarta', label: 'West Jakarta City, Special Region of Jakarta' },

  // Banten
  { value: 'Lebak Regency, Banten', label: 'Lebak Regency, Banten' },
  { value: 'Pandeglang Regency, Banten', label: 'Pandeglang Regency, Banten' },
  { value: 'Serang Regency, Banten', label: 'Serang Regency, Banten' },
  { value: 'Tangerang Regency, Banten', label: 'Tangerang Regency, Banten' },
  { value: 'Cilegon City, Banten', label: 'Cilegon City, Banten' },
  { value: 'Serang City, Banten', label: 'Serang City, Banten' },
  { value: 'South Tangerang City, Banten', label: 'South Tangerang City, Banten' },
  { value: 'Tangerang City, Banten', label: 'Tangerang City, Banten' },

  // West Java
  { value: 'Bandung Regency, West Java', label: 'Bandung Regency, West Java' },
  { value: 'Bekasi Regency, West Java', label: 'Bekasi Regency, West Java' },
  { value: 'Bogor Regency, West Java', label: 'Bogor Regency, West Java' },
  { value: 'Ciamis Regency, West Java', label: 'Ciamis Regency, West Java' },
  { value: 'Cianjur Regency, West Java', label: 'Cianjur Regency, West Java' },
  { value: 'Cirebon Regency, West Java', label: 'Cirebon Regency, West Java' },
  { value: 'Garut Regency, West Java', label: 'Garut Regency, West Java' },
  { value: 'Indramayu Regency, West Java', label: 'Indramayu Regency, West Java' },
  { value: 'Karawang Regency, West Java', label: 'Karawang Regency, West Java' },
  { value: 'Kuningan Regency, West Java', label: 'Kuningan Regency, West Java' },
  { value: 'Majalengka Regency, West Java', label: 'Majalengka Regency, West Java' },
  { value: 'Pangandaran Regency, West Java', label: 'Pangandaran Regency, West Java' },
  { value: 'Purwakarta Regency, West Java', label: 'Purwakarta Regency, West Java' },
  { value: 'Subang Regency, West Java', label: 'Subang Regency, West Java' },
  { value: 'Sukabumi Regency, West Java', label: 'Sukabumi Regency, West Java' },
  { value: 'Sumedang Regency, West Java', label: 'Sumedang Regency, West Java' },
  { value: 'Tasikmalaya Regency, West Java', label: 'Tasikmalaya Regency, West Java' },
  { value: 'West Bandung Regency, West Java', label: 'West Bandung Regency, West Java' },
  { value: 'Bandung City, West Java', label: 'Bandung City, West Java' },
  { value: 'Banjar City, West Java', label: 'Banjar City, West Java' },
  { value: 'Bekasi City, West Java', label: 'Bekasi City, West Java' },
  { value: 'Bogor City, West Java', label: 'Bogor City, West Java' },
  { value: 'Cimahi City, West Java', label: 'Cimahi City, West Java' },
  { value: 'Cirebon City, West Java', label: 'Cirebon City, West Java' },
  { value: 'Depok City, West Java', label: 'Depok City, West Java' },
  { value: 'Sukabumi City, West Java', label: 'Sukabumi City, West Java' },
  { value: 'Tasikmalaya City, West Java', label: 'Tasikmalaya City, West Java' },

  // Central Java
  { value: 'Banjarnegara Regency, Central Java', label: 'Banjarnegara Regency, Central Java' },
  { value: 'Banyumas Regency, Central Java', label: 'Banyumas Regency, Central Java' },
  { value: 'Batang Regency, Central Java', label: 'Batang Regency, Central Java' },
  { value: 'Blora Regency, Central Java', label: 'Blora Regency, Central Java' },
  { value: 'Boyolali Regency, Central Java', label: 'Boyolali Regency, Central Java' },
  { value: 'Brebes Regency, Central Java', label: 'Brebes Regency, Central Java' },
  { value: 'Cilacap Regency, Central Java', label: 'Cilacap Regency, Central Java' },
  { value: 'Demak Regency, Central Java', label: 'Demak Regency, Central Java' },
  { value: 'Grobogan Regency, Central Java', label: 'Grobogan Regency, Central Java' },
  { value: 'Jepara Regency, Central Java', label: 'Jepara Regency, Central Java' },
  { value: 'Karanganyar Regency, Central Java', label: 'Karanganyar Regency, Central Java' },
  { value: 'Kebumen Regency, Central Java', label: 'Kebumen Regency, Central Java' },
  { value: 'Kendal Regency, Central Java', label: 'Kendal Regency, Central Java' },
  { value: 'Klaten Regency, Central Java', label: 'Klaten Regency, Central Java' },
  { value: 'Kudus Regency, Central Java', label: 'Kudus Regency, Central Java' },
  { value: 'Magelang Regency, Central Java', label: 'Magelang Regency, Central Java' },
  { value: 'Pati Regency, Central Java', label: 'Pati Regency, Central Java' },
  { value: 'Pekalongan Regency, Central Java', label: 'Pekalongan Regency, Central Java' },
  { value: 'Pemalang Regency, Central Java', label: 'Pemalang Regency, Central Java' },
  { value: 'Purbalingga Regency, Central Java', label: 'Purbalingga Regency, Central Java' },
  { value: 'Purworejo Regency, Central Java', label: 'Purworejo Regency, Central Java' },
  { value: 'Rembang Regency, Central Java', label: 'Rembang Regency, Central Java' },
  { value: 'Semarang Regency, Central Java', label: 'Semarang Regency, Central Java' },
  { value: 'Sragen Regency, Central Java', label: 'Sragen Regency, Central Java' },
  { value: 'Sukoharjo Regency, Central Java', label: 'Sukoharjo Regency, Central Java' },
  { value: 'Tegal Regency, Central Java', label: 'Tegal Regency, Central Java' },
  { value: 'Temanggung Regency, Central Java', label: 'Temanggung Regency, Central Java' },
  { value: 'Wonogiri Regency, Central Java', label: 'Wonogiri Regency, Central Java' },
  { value: 'Wonosobo Regency, Central Java', label: 'Wonosobo Regency, Central Java' },
  { value: 'Magelang City, Central Java', label: 'Magelang City, Central Java' },
  { value: 'Pekalongan City, Central Java', label: 'Pekalongan City, Central Java' },
  { value: 'Salatiga City, Central Java', label: 'Salatiga City, Central Java' },
  { value: 'Semarang City, Central Java', label: 'Semarang City, Central Java' },
  { value: 'Surakarta City, Central Java', label: 'Surakarta City, Central Java' },
  { value: 'Tegal City, Central Java', label: 'Tegal City, Central Java' },

  // East Java
  { value: 'Bangkalan Regency, East Java', label: 'Bangkalan Regency, East Java' },
  { value: 'Banyuwangi Regency, East Java', label: 'Banyuwangi Regency, East Java' },
  { value: 'Blitar Regency, East Java', label: 'Blitar Regency, East Java' },
  { value: 'Bojonegoro Regency, East Java', label: 'Bojonegoro Regency, East Java' },
  { value: 'Bondowoso Regency, East Java', label: 'Bondowoso Regency, East Java' },
  { value: 'Gresik Regency, East Java', label: 'Gresik Regency, East Java' },
  { value: 'Jember Regency, East Java', label: 'Jember Regency, East Java' },
  { value: 'Jombang Regency, East Java', label: 'Jombang Regency, East Java' },
  { value: 'Kediri Regency, East Java', label: 'Kediri Regency, East Java' },
  { value: 'Lamongan Regency, East Java', label: 'Lamongan Regency, East Java' },
  { value: 'Lumajang Regency, East Java', label: 'Lumajang Regency, East Java' },
  { value: 'Madiun Regency, East Java', label: 'Madiun Regency, East Java' },
  { value: 'Magetan Regency, East Java', label: 'Magetan Regency, East Java' },
  { value: 'Malang Regency, East Java', label: 'Malang Regency, East Java' },
  { value: 'Mojokerto Regency, East Java', label: 'Mojokerto Regency, East Java' },
  { value: 'Nganjuk Regency, East Java', label: 'Nganjuk Regency, East Java' },
  { value: 'Ngawi Regency, East Java', label: 'Ngawi Regency, East Java' },
  { value: 'Pacitan Regency, East Java', label: 'Pacitan Regency, East Java' },
  { value: 'Pamekasan Regency, East Java', label: 'Pamekasan Regency, East Java' },
  { value: 'Pasuruan Regency, East Java', label: 'Pasuruan Regency, East Java' },
  { value: 'Ponorogo Regency, East Java', label: 'Ponorogo Regency, East Java' },
  { value: 'Probolinggo Regency, East Java', label: 'Probolinggo Regency, East Java' },
  { value: 'Sampang Regency, East Java', label: 'Sampang Regency, East Java' },
  { value: 'Sidoarjo Regency, East Java', label: 'Sidoarjo Regency, East Java' },
  { value: 'Situbondo Regency, East Java', label: 'Situbondo Regency, East Java' },
  { value: 'Sumenep Regency, East Java', label: 'Sumenep Regency, East Java' },
  { value: 'Trenggalek Regency, East Java', label: 'Trenggalek Regency, East Java' },
  { value: 'Tuban Regency, East Java', label: 'Tuban Regency, East Java' },
  { value: 'Tulungagung Regency, East Java', label: 'Tulungagung Regency, East Java' },
  { value: 'Batu City, East Java', label: 'Batu City, East Java' },
  { value: 'Blitar City, East Java', label: 'Blitar City, East Java' },
  { value: 'Kediri City, East Java', label: 'Kediri City, East Java' },
  { value: 'Madiun City, East Java', label: 'Madiun City, East Java' },
  { value: 'Malang City, East Java', label: 'Malang City, East Java' },
  { value: 'Mojokerto City, East Java', label: 'Mojokerto City, East Java' },
  { value: 'Pasuruan City, East Java', label: 'Pasuruan City, East Java' },
  { value: 'Probolinggo City, East Java', label: 'Probolinggo City, East Java' },
  { value: 'Surabaya City, East Java', label: 'Surabaya City, East Java' },

  // Special Region of Yogyakarta
  { value: 'Bantul Regency, Special Region of Yogyakarta', label: 'Bantul Regency, Special Region of Yogyakarta' },
  { value: 'Gunung Kidul Regency, Special Region of Yogyakarta', label: 'Gunung Kidul Regency, Special Region of Yogyakarta' },
  { value: 'Kulon Progo Regency, Special Region of Yogyakarta', label: 'Kulon Progo Regency, Special Region of Yogyakarta' },
  { value: 'Sleman Regency, Special Region of Yogyakarta', label: 'Sleman Regency, Special Region of Yogyakarta' },
  { value: 'Yogyakarta City, Special Region of Yogyakarta', label: 'Yogyakarta City, Special Region of Yogyakarta' },

  // Bali
  { value: 'Badung Regency, Bali', label: 'Badung Regency, Bali' },
  { value: 'Bangli Regency, Bali', label: 'Bangli Regency, Bali' },
  { value: 'Buleleng Regency, Bali', label: 'Buleleng Regency, Bali' },
  { value: 'Gianyar Regency, Bali', label: 'Gianyar Regency, Bali' },
  { value: 'Jembrana Regency, Bali', label: 'Jembrana Regency, Bali' },
  { value: 'Karangasem Regency, Bali', label: 'Karangasem Regency, Bali' },
  { value: 'Klungkung Regency, Bali', label: 'Klungkung Regency, Bali' },
  { value: 'Tabanan Regency, Bali', label: 'Tabanan Regency, Bali' },
  { value: 'Denpasar City, Bali', label: 'Denpasar City, Bali' },

  // West Nusa Tenggara
  { value: 'Bima Regency, West Nusa Tenggara', label: 'Bima Regency, West Nusa Tenggara' },
  { value: 'Central Lombok Regency, West Nusa Tenggara', label: 'Central Lombok Regency, West Nusa Tenggara' },
  { value: 'Dompu Regency, West Nusa Tenggara', label: 'Dompu Regency, West Nusa Tenggara' },
  { value: 'East Lombok Regency, West Nusa Tenggara', label: 'East Lombok Regency, West Nusa Tenggara' },
  { value: 'North Lombok Regency, West Nusa Tenggara', label: 'North Lombok Regency, West Nusa Tenggara' },
  { value: 'Sumbawa Regency, West Nusa Tenggara', label: 'Sumbawa Regency, West Nusa Tenggara' },
  { value: 'West Lombok Regency, West Nusa Tenggara', label: 'West Lombok Regency, West Nusa Tenggara' },
  { value: 'West Sumbawa Regency, West Nusa Tenggara', label: 'West Sumbawa Regency, West Nusa Tenggara' },
  { value: 'Bima City, West Nusa Tenggara', label: 'Bima City, West Nusa Tenggara' },
  { value: 'Mataram City, West Nusa Tenggara', label: 'Mataram City, West Nusa Tenggara' },

  // East Nusa Tenggara
  { value: 'Alor Regency, East Nusa Tenggara', label: 'Alor Regency, East Nusa Tenggara' },
  { value: 'Belu Regency, East Nusa Tenggara', label: 'Belu Regency, East Nusa Tenggara' },
  { value: 'Central Sumba Regency, East Nusa Tenggara', label: 'Central Sumba Regency, East Nusa Tenggara' },
  { value: 'East Flores Regency, East Nusa Tenggara', label: 'East Flores Regency, East Nusa Tenggara' },
  { value: 'East Manggarai Regency, East Nusa Tenggara', label: 'East Manggarai Regency, East Nusa Tenggara' },
  { value: 'East Sumba Regency, East Nusa Tenggara', label: 'East Sumba Regency, East Nusa Tenggara' },
  { value: 'Ende Regency, East Nusa Tenggara', label: 'Ende Regency, East Nusa Tenggara' },
  { value: 'Kupang Regency, East Nusa Tenggara', label: 'Kupang Regency, East Nusa Tenggara' },
  { value: 'Lembata Regency, East Nusa Tenggara', label: 'Lembata Regency, East Nusa Tenggara' },
  { value: 'Malaka Regency, East Nusa Tenggara', label: 'Malaka Regency, East Nusa Tenggara' },
  { value: 'Manggarai Regency, East Nusa Tenggara', label: 'Manggarai Regency, East Nusa Tenggara' },
  { value: 'Nagekeo Regency, East Nusa Tenggara', label: 'Nagekeo Regency, East Nusa Tenggara' },
  { value: 'Ngada Regency, East Nusa Tenggara', label: 'Ngada Regency, East Nusa Tenggara' },
  { value: 'North Central Timor Regency, East Nusa Tenggara', label: 'North Central Timor Regency, East Nusa Tenggara' },
  { value: 'Rote Ndao Regency, East Nusa Tenggara', label: 'Rote Ndao Regency, East Nusa Tenggara' },
  { value: 'Sabu Raijua Regency, East Nusa Tenggara', label: 'Sabu Raijua Regency, East Nusa Tenggara' },
  { value: 'Sikka Regency, East Nusa Tenggara', label: 'Sikka Regency, East Nusa Tenggara' },
  { value: 'South Central Timor Regency, East Nusa Tenggara', label: 'South Central Timor Regency, East Nusa Tenggara' },
  { value: 'Southwest Sumba Regency, East Nusa Tenggara', label: 'Southwest Sumba Regency, East Nusa Tenggara' },
  { value: 'West Manggarai Regency, East Nusa Tenggara', label: 'West Manggarai Regency, East Nusa Tenggara' },
  { value: 'West Sumba Regency, East Nusa Tenggara', label: 'West Sumba Regency, East Nusa Tenggara' },
  { value: 'Kupang City, East Nusa Tenggara', label: 'Kupang City, East Nusa Tenggara' },

  // West Kalimantan
  { value: 'Bengkayang Regency, West Kalimantan', label: 'Bengkayang Regency, West Kalimantan' },
  { value: 'Kapuas Hulu Regency, West Kalimantan', label: 'Kapuas Hulu Regency, West Kalimantan' },
  { value: 'North Kayong Regency, West Kalimantan', label: 'North Kayong Regency, West Kalimantan' },
  { value: 'Ketapang Regency, West Kalimantan', label: 'Ketapang Regency, West Kalimantan' },
  { value: 'Kubu Raya Regency, West Kalimantan', label: 'Kubu Raya Regency, West Kalimantan' },
  { value: 'Landak Regency, West Kalimantan', label: 'Landak Regency, West Kalimantan' },
  { value: 'Melawi Regency, West Kalimantan', label: 'Melawi Regency, West Kalimantan' },
  { value: 'Mempawah Regency, West Kalimantan', label: 'Mempawah Regency, West Kalimantan' },
  { value: 'Sambas Regency, West Kalimantan', label: 'Sambas Regency, West Kalimantan' },
  { value: 'Sanggau Regency, West Kalimantan', label: 'Sanggau Regency, West Kalimantan' },
  { value: 'Sekadau Regency, West Kalimantan', label: 'Sekadau Regency, West Kalimantan' },
  { value: 'Sintang Regency, West Kalimantan', label: 'Sintang Regency, West Kalimantan' },
  { value: 'Pontianak City, West Kalimantan', label: 'Pontianak City, West Kalimantan' },
  { value: 'Singkawang City, West Kalimantan', label: 'Singkawang City, West Kalimantan' },

  // South Kalimantan
  { value: 'Balangan Regency, South Kalimantan', label: 'Balangan Regency, South Kalimantan' },
  { value: 'Banjar Regency, South Kalimantan', label: 'Banjar Regency, South Kalimantan' },
  { value: 'Barito Kuala Regency, South Kalimantan', label: 'Barito Kuala Regency, South Kalimantan' },
  { value: 'Central Hulu Sungai Regency, South Kalimantan', label: 'Central Hulu Sungai Regency, South Kalimantan' },
  { value: 'Kotabaru Regency, South Kalimantan', label: 'Kotabaru Regency, South Kalimantan' },
  { value: 'North Hulu Sungai Regency, South Kalimantan', label: 'North Hulu Sungai Regency, South Kalimantan' },
  { value: 'South Hulu Sungai Regency, South Kalimantan', label: 'South Hulu Sungai Regency, South Kalimantan' },
  { value: 'Tabalong Regency, South Kalimantan', label: 'Tabalong Regency, South Kalimantan' },
  { value: 'Tanah Laut Regency, South Kalimantan', label: 'Tanah Laut Regency, South Kalimantan' },
  { value: 'Tanah Bumbu Regency, South Kalimantan', label: 'Tanah Bumbu Regency, South Kalimantan' },
  { value: 'Tapin Regency, South Kalimantan', label: 'Tapin Regency, South Kalimantan' },
  { value: 'Banjarbaru City, South Kalimantan', label: 'Banjarbaru City, South Kalimantan' },
  { value: 'Banjarmasin City, South Kalimantan', label: 'Banjarmasin City, South Kalimantan' },

  // Central Kalimantan
  { value: 'East Barito Regency, Central Kalimantan', label: 'East Barito Regency, Central Kalimantan' },
  { value: 'East Kotawaringin Regency, Central Kalimantan', label: 'East Kotawaringin Regency, Central Kalimantan' },
  { value: 'Gunung Mas Regency, Central Kalimantan', label: 'Gunung Mas Regency, Central Kalimantan' },
  { value: 'Kapuas Regency, Central Kalimantan', label: 'Kapuas Regency, Central Kalimantan' },
  { value: 'Katingan Regency, Central Kalimantan', label: 'Katingan Regency, Central Kalimantan' },
  { value: 'Lamandau Regency, Central Kalimantan', label: 'Lamandau Regency, Central Kalimantan' },
  { value: 'Murung Raya Regency, Central Kalimantan', label: 'Murung Raya Regency, Central Kalimantan' },
  { value: 'North Barito Regency, Central Kalimantan', label: 'North Barito Regency, Central Kalimantan' },
  { value: 'Pulang Pisau Regency, Central Kalimantan', label: 'Pulang Pisau Regency, Central Kalimantan' },
  { value: 'Sukamara Regency, Central Kalimantan', label: 'Sukamara Regency, Central Kalimantan' },
  { value: 'Seruyan Regency, Central Kalimantan', label: 'Seruyan Regency, Central Kalimantan' },
  { value: 'South Barito Regency, Central Kalimantan', label: 'South Barito Regency, Central Kalimantan' },
  { value: 'West Kotawaringin Regency, Central Kalimantan', label: 'West Kotawaringin Regency, Central Kalimantan' },
  { value: 'Palangka Raya City, Central Kalimantan', label: 'Palangka Raya City, Central Kalimantan' },

  // East Kalimantan
  { value: 'Berau Regency, East Kalimantan', label: 'Berau Regency, East Kalimantan' },
  { value: 'East Kutai Regency, East Kalimantan', label: 'East Kutai Regency, East Kalimantan' },
  { value: 'Kutai Kartanegara Regency, East Kalimantan', label: 'Kutai Kartanegara Regency, East Kalimantan' },
  { value: 'Mahakam Ulu Regency, East Kalimantan', label: 'Mahakam Ulu Regency, East Kalimantan' },
  { value: 'Paser Regency, East Kalimantan', label: 'Paser Regency, East Kalimantan' },
  { value: 'Penajam North Paser Regency, East Kalimantan', label: 'Penajam North Paser Regency, East Kalimantan' },
  { value: 'West Kutai Regency, East Kalimantan', label: 'West Kutai Regency, East Kalimantan' },
  { value: 'Balikpapan City, East Kalimantan', label: 'Balikpapan City, East Kalimantan' },
  { value: 'Bontang City, East Kalimantan', label: 'Bontang City, East Kalimantan' },
  { value: 'Samarinda City, East Kalimantan', label: 'Samarinda City, East Kalimantan' },

  // North Kalimantan
  { value: 'Bulungan Regency, North Kalimantan', label: 'Bulungan Regency, North Kalimantan' },
  { value: 'Malinau Regency, North Kalimantan', label: 'Malinau Regency, North Kalimantan' },
  { value: 'Nunukan Regency, North Kalimantan', label: 'Nunukan Regency, North Kalimantan' },
  { value: 'Tana Tidung Regency, North Kalimantan', label: 'Tana Tidung Regency, North Kalimantan' },
  { value: 'Tarakan City, North Kalimantan', label: 'Tarakan City, North Kalimantan' },

  // Gorontalo
  { value: 'Boalemo Regency, Gorontalo', label: 'Boalemo Regency, Gorontalo' },
  { value: 'Bone Bolango Regency, Gorontalo', label: 'Bone Bolango Regency, Gorontalo' },
  { value: 'Gorontalo Regency, Gorontalo', label: 'Gorontalo Regency, Gorontalo' },
  { value: 'North Gorontalo Regency, Gorontalo', label: 'North Gorontalo Regency, Gorontalo' },
  { value: 'Pohuwato Regency, Gorontalo', label: 'Pohuwato Regency, Gorontalo' },
  { value: 'Gorontalo City, Gorontalo', label: 'Gorontalo City, Gorontalo' },

  // South Sulawesi
  { value: 'Bantaeng Regency, South Sulawesi', label: 'Bantaeng Regency, South Sulawesi' },
  { value: 'Barru Regency, South Sulawesi', label: 'Barru Regency, South Sulawesi' },
  { value: 'Bone Regency, South Sulawesi', label: 'Bone Regency, South Sulawesi' },
  { value: 'Bulukumba Regency, South Sulawesi', label: 'Bulukumba Regency, South Sulawesi' },
  { value: 'East Luwu Regency, South Sulawesi', label: 'East Luwu Regency, South Sulawesi' },
  { value: 'Enrekang Regency, South Sulawesi', label: 'Enrekang Regency, South Sulawesi' },
  { value: 'Gowa Regency, South Sulawesi', label: 'Gowa Regency, South Sulawesi' },
  { value: 'Jeneponto Regency, South Sulawesi', label: 'Jeneponto Regency, South Sulawesi' },
  { value: 'Luwu Regency, South Sulawesi', label: 'Luwu Regency, South Sulawesi' },
  { value: 'North Luwu Regency, South Sulawesi', label: 'North Luwu Regency, South Sulawesi' },
  { value: 'North Toraja Regency, South Sulawesi', label: 'North Toraja Regency, South Sulawesi' },
  { value: 'Maros Regency, South Sulawesi', label: 'Maros Regency, South Sulawesi' },
  { value: 'Pangkajene and Islands Regency, South Sulawesi', label: 'Pangkajene and Islands Regency, South Sulawesi' },
  { value: 'Pinrang Regency, South Sulawesi', label: 'Pinrang Regency, South Sulawesi' },
  { value: 'Selayar Islands Regency, South Sulawesi', label: 'Selayar Islands Regency, South Sulawesi' },
  { value: 'Sinjai Regency, South Sulawesi', label: 'Sinjai Regency, South Sulawesi' },
  { value: 'Sidenreng Rappang Regency, South Sulawesi', label: 'Sidenreng Rappang Regency, South Sulawesi' },
  { value: 'Soppeng Regency, South Sulawesi', label: 'Soppeng Regency, South Sulawesi' },
  { value: 'Takalar Regency, South Sulawesi', label: 'Takalar Regency, South Sulawesi' },
  { value: 'Tana Toraja Regency, South Sulawesi', label: 'Tana Toraja Regency, South Sulawesi' },
  { value: 'Wajo Regency, South Sulawesi', label: 'Wajo Regency, South Sulawesi' },
  { value: 'Makassar City, South Sulawesi', label: 'Makassar City, South Sulawesi' },
  { value: 'Palopo City, South Sulawesi', label: 'Palopo City, South Sulawesi' },
  { value: 'Parepare City, South Sulawesi', label: 'Parepare City, South Sulawesi' },

  // West Sulawesi
  { value: 'Central Mamuju Regency, West Sulawesi', label: 'Central Mamuju Regency, West Sulawesi' },
  { value: 'Majene Regency, West Sulawesi', label: 'Majene Regency, West Sulawesi' },
  { value: 'Mamasa Regency, West Sulawesi', label: 'Mamasa Regency, West Sulawesi' },
  { value: 'Mamuju Regency, West Sulawesi', label: 'Mamuju Regency, West Sulawesi' },
  { value: 'Pasangkayu Regency, West Sulawesi', label: 'Pasangkayu Regency, West Sulawesi' },
  { value: 'Polewali Mandar Regency, West Sulawesi', label: 'Polewali Mandar Regency, West Sulawesi' },

  // Southeast Sulawesi
  { value: 'Bombana Regency, Southeast Sulawesi', label: 'Bombana Regency, Southeast Sulawesi' },
  { value: 'Buton Regency, Southeast Sulawesi', label: 'Buton Regency, Southeast Sulawesi' },
  { value: 'Central Buton Regency, Southeast Sulawesi', label: 'Central Buton Regency, Southeast Sulawesi' },
  { value: 'East Kolaka Regency, Southeast Sulawesi', label: 'East Kolaka Regency, Southeast Sulawesi' },
  { value: 'Kolaka Regency, Southeast Sulawesi', label: 'Kolaka Regency, Southeast Sulawesi' },
  { value: 'Konawe Regency, Southeast Sulawesi', label: 'Konawe Regency, Southeast Sulawesi' },
  { value: 'Konawe Islands Regency, Southeast Sulawesi', label: 'Konawe Islands Regency, Southeast Sulawesi' },
  { value: 'Muna Regency, Southeast Sulawesi', label: 'Muna Regency, Southeast Sulawesi' },
  { value: 'North Buton Regency, Southeast Sulawesi', label: 'North Buton Regency, Southeast Sulawesi' },
  { value: 'North Kolaka Regency, Southeast Sulawesi', label: 'North Kolaka Regency, Southeast Sulawesi' },
  { value: 'North Konawe Regency, Southeast Sulawesi', label: 'North Konawe Regency, Southeast Sulawesi' },
  { value: 'South Buton Regency, Southeast Sulawesi', label: 'South Buton Regency, Southeast Sulawesi' },
  { value: 'South Konawe Regency, Southeast Sulawesi', label: 'South Konawe Regency, Southeast Sulawesi' },
  { value: 'Wakatobi Regency, Southeast Sulawesi', label: 'Wakatobi Regency, Southeast Sulawesi' },
  { value: 'West Muna Regency, Southeast Sulawesi', label: 'West Muna Regency, Southeast Sulawesi' },
  { value: 'Baubau City, Southeast Sulawesi', label: 'Baubau City, Southeast Sulawesi' },
  { value: 'Kendari City, Southeast Sulawesi', label: 'Kendari City, Southeast Sulawesi' },

  // Central Sulawesi
  { value: 'Banggai Regency, Central Sulawesi', label: 'Banggai Regency, Central Sulawesi' },
  { value: 'Banggai Islands Regency, Central Sulawesi', label: 'Banggai Islands Regency, Central Sulawesi' },
  { value: 'Banggai Laut Regency, Central Sulawesi', label: 'Banggai Laut Regency, Central Sulawesi' },
  { value: 'Buol Regency, Central Sulawesi', label: 'Buol Regency, Central Sulawesi' },
  { value: 'Donggala Regency, Central Sulawesi', label: 'Donggala Regency, Central Sulawesi' },
  { value: 'Morowali Regency, Central Sulawesi', label: 'Morowali Regency, Central Sulawesi' },
  { value: 'North Morowali Regency, Central Sulawesi', label: 'North Morowali Regency, Central Sulawesi' },
  { value: 'Parigi Moutong Regency, Central Sulawesi', label: 'Parigi Moutong Regency, Central Sulawesi' },
  { value: 'Poso Regency, Central Sulawesi', label: 'Poso Regency, Central Sulawesi' },
  { value: 'Sigi Regency, Central Sulawesi', label: 'Sigi Regency, Central Sulawesi' },
  { value: 'Tojo Una-Una Regency, Central Sulawesi', label: 'Tojo Una-Una Regency, Central Sulawesi' },
  { value: 'Tolitoli Regency, Central Sulawesi', label: 'Tolitoli Regency, Central Sulawesi' },
  { value: 'Palu City, Central Sulawesi', label: 'Palu City, Central Sulawesi' },

  // North Sulawesi
  { value: 'Bolaang Mongondow Regency, North Sulawesi', label: 'Bolaang Mongondow Regency, North Sulawesi' },
  { value: 'East Bolaang Mongondow Regency, North Sulawesi', label: 'East Bolaang Mongondow Regency, North Sulawesi' },
  { value: 'Minahasa Regency, North Sulawesi', label: 'Minahasa Regency, North Sulawesi' },
  { value: 'North Bolaang Mongondow Regency, North Sulawesi', label: 'North Bolaang Mongondow Regency, North Sulawesi' },
  { value: 'North Minahasa Regency, North Sulawesi', label: 'North Minahasa Regency, North Sulawesi' },
  { value: 'Sangihe Islands Regency, North Sulawesi', label: 'Sangihe Islands Regency, North Sulawesi' },
  { value: 'Sitaro Islands Regency, North Sulawesi', label: 'Sitaro Islands Regency, North Sulawesi' },
  { value: 'South Bolaang Mongondow Regency, North Sulawesi', label: 'South Bolaang Mongondow Regency, North Sulawesi' },
  { value: 'South Minahasa Regency, North Sulawesi', label: 'South Minahasa Regency, North Sulawesi' },
  { value: 'Southeast Minahasa Regency, North Sulawesi', label: 'Southeast Minahasa Regency, North Sulawesi' },
  { value: 'Talaud Islands Regency, North Sulawesi', label: 'Talaud Islands Regency, North Sulawesi' },
  { value: 'Bitung City, North Sulawesi', label: 'Bitung City, North Sulawesi' },
  { value: 'Kotamobagu City, North Sulawesi', label: 'Kotamobagu City, North Sulawesi' },
  { value: 'Manado City, North Sulawesi', label: 'Manado City, North Sulawesi' },
  { value: 'Tomohon City, North Sulawesi', label: 'Tomohon City, North Sulawesi' },

  // Maluku
  { value: 'Aru Islands Regency, Maluku', label: 'Aru Islands Regency, Maluku' },
  { value: 'Buru Regency, Maluku', label: 'Buru Regency, Maluku' },
  { value: 'Central Maluku Regency, Maluku', label: 'Central Maluku Regency, Maluku' },
  { value: 'East Seram Regency, Maluku', label: 'East Seram Regency, Maluku' },
  { value: 'South Buru Regency, Maluku', label: 'South Buru Regency, Maluku' },
  { value: 'Southeast Maluku Regency, Maluku', label: 'Southeast Maluku Regency, Maluku' },
  { value: 'Southwest Maluku Regency, Maluku', label: 'Southwest Maluku Regency, Maluku' },
  { value: 'Tanimbar Islands Regency, Maluku', label: 'Tanimbar Islands Regency, Maluku' },
  { value: 'West Seram Regency, Maluku', label: 'West Seram Regency, Maluku' },
  { value: 'Ambon City, Maluku', label: 'Ambon City, Maluku' },
  { value: 'Tual City, Maluku', label: 'Tual City, Maluku' },

  // North Maluku
  { value: 'Central Halmahera Regency, North Maluku', label: 'Central Halmahera Regency, North Maluku' },
  { value: 'East Halmahera Regency, North Maluku', label: 'East Halmahera Regency, North Maluku' },
  { value: 'Morotai Island Regency, North Maluku', label: 'Morotai Island Regency, North Maluku' },
  { value: 'North Halmahera Regency, North Maluku', label: 'North Halmahera Regency, North Maluku' },
  { value: 'South Halmahera Regency, North Maluku', label: 'South Halmahera Regency, North Maluku' },
  { value: 'Sula Islands Regency, North Maluku', label: 'Sula Islands Regency, North Maluku' },
  { value: 'Taliabu Island Regency, North Maluku', label: 'Taliabu Island Regency, North Maluku' },
  { value: 'West Halmahera Regency, North Maluku', label: 'West Halmahera Regency, North Maluku' },
  { value: 'Ternate City, North Maluku', label: 'Ternate City, North Maluku' },
  { value: 'Tidore City, North Maluku', label: 'Tidore City, North Maluku' },

  // West Papua
  { value: 'Fakfak Regency, West Papua', label: 'Fakfak Regency, West Papua' },
  { value: 'Kaimana Regency, West Papua', label: 'Kaimana Regency, West Papua' },
  { value: 'Manokwari Regency, West Papua', label: 'Manokwari Regency, West Papua' },
  { value: 'Arfak Mountains Regency, West Papua', label: 'Arfak Mountains Regency, West Papua' },
  { value: 'South Manokwari Regency, West Papua', label: 'South Manokwari Regency, West Papua' },
  { value: 'Teluk Bintuni Regency, West Papua', label: 'Teluk Bintuni Regency, West Papua' },
  { value: 'Teluk Wondama Regency, West Papua', label: 'Teluk Wondama Regency, West Papua' },

  // Papua
  { value: 'Biak Numfor Regency, Papua', label: 'Biak Numfor Regency, Papua' },
  { value: 'Jayapura Regency, Papua', label: 'Jayapura Regency, Papua' },
  { value: 'Keerom Regency, Papua', label: 'Keerom Regency, Papua' },
  { value: 'Mamberamo Raya Regency, Papua', label: 'Mamberamo Raya Regency, Papua' },
  { value: 'Sarmi Regency, Papua', label: 'Sarmi Regency, Papua' },
  { value: 'Supiori Regency, Papua', label: 'Supiori Regency, Papua' },
  { value: 'Waropen Regency, Papua', label: 'Waropen Regency, Papua' },
  { value: 'Yapen Islands Regency, Papua', label: 'Yapen Islands Regency, Papua' },
  { value: 'Jayapura City, Papua', label: 'Jayapura City, Papua' },

  // Highland Papua
  { value: 'Central Mamberamo Regency, Highland Papua', label: 'Central Mamberamo Regency, Highland Papua' },
  { value: 'Jayawijaya Regency, Highland Papua', label: 'Jayawijaya Regency, Highland Papua' },
  { value: 'Lanny Jaya Regency, Highland Papua', label: 'Lanny Jaya Regency, Highland Papua' },
  { value: 'Nduga Regency, Highland Papua', label: 'Nduga Regency, Highland Papua' },
  { value: 'Pegunungan Bintang Regency, Highland Papua', label: 'Pegunungan Bintang Regency, Highland Papua' },
  { value: 'Tolikara Regency, Highland Papua', label: 'Tolikara Regency, Highland Papua' },
  { value: 'Yahukimo Regency, Highland Papua', label: 'Yahukimo Regency, Highland Papua' },
  { value: 'Yalimo Regency, Highland Papua', label: 'Yalimo Regency, Highland Papua' },

  // Central Papua
  { value: 'Deiyai Regency, Central Papua', label: 'Deiyai Regency, Central Papua' },
  { value: 'Dogiyai Regency, Central Papua', label: 'Dogiyai Regency, Central Papua' },
  { value: 'Intan Jaya Regency, Central Papua', label: 'Intan Jaya Regency, Central Papua' },
  { value: 'Mimika Regency, Central Papua', label: 'Mimika Regency, Central Papua' },
  { value: 'Nabire Regency, Central Papua', label: 'Nabire Regency, Central Papua' },
  { value: 'Paniai Regency, Central Papua', label: 'Paniai Regency, Central Papua' },
  { value: 'Puncak Regency, Central Papua', label: 'Puncak Regency, Central Papua' },
  { value: 'Puncak Jaya Regency, Central Papua', label: 'Puncak Jaya Regency, Central Papua' },

  // South Papua
  { value: 'Asmat Regency, South Papua', label: 'Asmat Regency, South Papua' },
  { value: 'Boven Digoel Regency, South Papua', label: 'Boven Digoel Regency, South Papua' },
  { value: 'Mappi Regency, South Papua', label: 'Mappi Regency, South Papua' },
  { value: 'Merauke Regency, South Papua', label: 'Merauke Regency, South Papua' },

  // Southwest Papua
  { value: 'Maybrat Regency, Southwest Papua', label: 'Maybrat Regency, Southwest Papua' },
  { value: 'Raja Ampat Regency, Southwest Papua', label: 'Raja Ampat Regency, Southwest Papua' },
  { value: 'Sorong Regency, Southwest Papua', label: 'Sorong Regency, Southwest Papua' },
  { value: 'South Sorong Regency, Southwest Papua', label: 'South Sorong Regency, Southwest Papua' },
  { value: 'Tambrauw Regency, Southwest Papua', label: 'Tambrauw Regency, Southwest Papua' },
  { value: 'Sorong City, Southwest Papua', label: 'Sorong City, Southwest Papua' },
];